### PR TITLE
Update Mailkit to 4.7 and upgrade vulnerable components

### PR DESCRIPTION
**Pull request by MarkMenchavez**
Upgrade Microsoft Identity Client to 4.61.1 due to vulnerabilities detected

Upgrade MailKit to 4.6.0

### CODE REVIEW

**Comment by neozhu** [comment]
@JohnCampionJr   can you  merge  it

**Comment by neozhu** [comment]
@MarkMenchavez 
image

I encountered a warning while compiling. Could you please check it out?

**Comment by MarkMenchavez** [comment]
> @MarkMenchavez image
> 
> I encountered a warning while compiling. Could you please check it out?

Working on it... When I did the PR, I used the latest package dependencies.  They are now flagged as vulnerable.

**Comment by MarkMenchavez** [comment]
@neozhu Please check if it's still has the vulnerable components.
Hope this gets merged soon.

Thanks.

**Comment by neozhu** [comment]
@JohnCampionJr could you please review and merge this PR

**Comment by neozhu** [comment]
@JohnCampionJr 
could you please review and merge it?
Thanks for your time!

**Pull request merged**
